### ISSUE TITLE
Operator Degraded with monitoring-edit aggregation rbac permissions eror

### ISSUE THREAD

**Issue by stujb** [openshift/cluster-monitoring-operator#1501]
$ oc version
Client Version: 4.8.0-0.okd-2021-11-14-052418
Server Version: 4.8.0-0.okd-2021-10-24-061736
Kubernetes Version: v1.21.2-1505+6438632813d726-dirty

cluster-monitoring-operator is reporting as degraded with the following error in the pod logs

I1201 16:47:31.354041       1 tasks.go:67] ran task 4 of 15: Updating Prometheus-k8s
I1201 16:47:31.354071       1 operator.go:492] ClusterOperator reconciliation failed (attempt 123), retrying. Err: running task Updating Cluster Monitoring Operator failed: reconciling monitoring-edit ClusterRole failed: updating ClusterRole object failed: clusterroles.rbac.authorization.k8s.io "monitoring-edit" is forbidden: must have cluster-admin privileges to use the aggregationRule
E1201 16:47:31.354082       1 operator.go:401] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E1201 16:47:31.354095       1 operator.go:402] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Cluster Monitoring Operator failed: reconciling monitoring-edit ClusterRole failed: updating ClusterRole object failed: clusterroles.rbac.authorization.k8s.io "monitoring-edit" is forbidden: must have cluster-admin privileges to use the aggregationRule

It's not clear to me why this is happening. I don't think I have set any RBAC config that would cause this to break

**Comment by stujb** [comment]
This was due to conflict in the name of a manually installed operatorgroup being called 'monitoring'. Changed the name of this operatorgroup and the issue was resolved

**Comment by joyartoun** [comment]
I propose reopening this issue as this is still present in version 4.11.0-0.okd-2022-07-29-154152.
